### ISSUE TITLE
build folder missing.

### ISSUE THREAD

**Issue by sjkurani** [IncredibleWeb/pwa-tutorial#7]
I cloned the repository to my local system and tried to execute the project then in console i am able to find that the build directory under demo/js is missing.

Please find attached screen shot.

![screenshot from 2016-12-06 17 58 38](https://cloud.githubusercontent.com/assets/2835033/20925548/aa2ff716-bbdd-11e6-90ab-020a99fe8a45.png)

I can able to get the files from
https://incredibleweb.github.io/pwa-tutorial/js/build/vendor.min.js
and 
https://incredibleweb.github.io/pwa-tutorial/js/build/script.min.js

but these files were missing while getting clone of the repository.

**Comment by kevinfarrugia** [comment]
@sjkurani you are required to run grunt, i.e. open the command line in the root folder and execute:

`grunt dev`
