### ISSUE TITLE
do not receive the banner

### ISSUE THREAD

**Issue by yunushkin88** [IncredibleWeb/pwa-tutorial#8]
Hello!!! I did as described in your manual https://www.smashingmagazine.com/2016/08/a-beginners-guide-to-progressive-web-apps/    but for some reason I do not receive the setup banner are described in the manifest.  I use github pages. I put everything in the project folder. Say what could be the problem I would be very grateful?)

**Comment by kevinfarrugia** [comment]
Could you share a URL?

Also does the banner show for https://incredibleweb.github.io/pwa-tutorial/ ?

FYI:
**You said that I will only get the banner if I visit the site over a certain period of time. How can I test this faster?** Enable chrome://flags/#bypass-app-banner-engagement-checks and you will see the banner as long as you have a manifest (configured correctly) and are on HTTPS and have a service worker. (taken from https://developers.google.com/web/updates/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android)
